name: 'Self-Hosted Runner'
description: 'Stopping/Starting/Removing a self-hosted runner for github repo'

inputs:
  token:
    description: 'GitHub Repo scoped token'
    required: True
  runner_name:
    description: 'Runner registered name on GitHub Actions'
    required: True
  runner_ip:
    description: 'Private IP v4 addres for the EC2 instance Runner'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - run: pip install boto3
      shell: bash

    - name: Ec2 Runner (running python script)
      id: ec2-runner
      env:
        E_RUNNER_NAME: ${{ inputs.runner_name }}
        E_RUNNER_IP: ${{ inputs.runner_ip }}
      run: |
        ids="$(python "${{ github.action_path }}/../aws_runner_handler.py" remove)"
        echo "EC2_ID=$(echo "${ids}" | cut -f1 -d',')" | tee -a $GITHUB_OUTPUT
        echo "REQUEST_ID=$(echo "${ids}" | cut -f2 -d',')" | tee -a $GITHUB_OUTPUT
      shell: bash

    - name: Get Self-hosted Runner ID from GitHub
      id: get-runner-id
      shell: bash
      run: |
        gh_runner_id="$(curl -s -u "git:${{ inputs.token }}" \
                             -H "Accept: application/vnd.github.v3+json" \
                             ${{ github.api_url }}/repos/${{ github.repository }}/actions/runners \
                        | jq -r ".runners[] | select(.name | contains(\"${{ inputs.runner_name }}\")) | .id")"
        echo "ID=${gh_runner_id}" | tee -a $GITHUB_OUTPUT

    - name: Remove Self-hosted Runner from GitHub
      shell: bash
      run: |
        curl -X DELETE -L -o - -u "git:${{ inputs.token }}" \
              -H "Accept: application/vnd.github.v3+json" \
              "${{ github.api_url }}/repos/${{ github.repository }}/actions/runners/${{ steps.get-runner-id.outputs.ID }}"
