name: remove self-hosted runner
description: remove self-hosted runner
inputs:
  name:
    description: 'self-hosted runner name'
    required: true
  scope:
    description: 'org or repo, organization or repository level'
    required: false
  token:
    description: 'GitHub self-hosted runner registration token'
    required: false
  runners_data_file:
    description: 'where to get the csv file for runners data'
    required: false

runs:
  using: "composite"
  steps:
    - name: prepare settings
      id: settings
      shell: bash
      run: |
        has_error="no"

        if [[ "${{ inputs.scope }}" != "" ]]; then
          scope="${{ inputs.scope }}"
        else
          if [[ "${{ env.gha-runner-scope }}" != "" ]]; then
            scope="${{ env.gha-runner-scope }}"
          else
            scope="repo"
          fi
        fi

        if [[ "${{ inputs.token }}" != "" ]]; then
          token="${{ inputs.token }}"
        else
          if [[ "${{ env.gha-runner-token }}" != "" ]]; then
            token="${{ env.gha-runner-token }}"
          else
            echo "::error ::Missing token in runner-remove action"
            has_error="yes"
          fi
        fi

        if [[ "${{ inputs.runners_data_file }}" != "" ]]; then
          runners_data_file="${{ inputs.runners_data_file }}"
        else
          if [[ "${{ env.gha-runner-runners_data_file }}" != "" ]]; then
            runners_data_file="${{ env.gha-runner-runners_data_file }}"
          else
            echo "::error ::Missing runners_data_file in runner-remove action"
            has_error="yes"
          fi
        fi

        if [[ "${has_error}" == "yes" ]]; then exit 1; fi

        echo "scope=${scope}" | tee -a $GITHUB_OUTPUT
        echo "token=${token}" | tee -a $GITHUB_OUTPUT
        echo "runners_data_file=${runners_data_file}" | tee -a $GITHUB_OUTPUT

    - uses: acerorg/gha-runner/use-python@MIN-340

    - name: Get runner details
      id: get-runner-details
      uses: acerorg/gha-runner/get-runner-details-from-csv@MIN-340
      with:
        data_file_path: ${{ steps.settings.outputs.runners_data_file }}
        name: ${{ inputs.name }}

    - name: Get Subnet Id and IP
      id: get-subnet-id-ip
      uses: acerorg/gha-runner/get-ip-subnet-by-cidr@MIN-340
      with:
        ip_cidr: ${{ steps.get-runner-details.outputs.IP_CIDR }}

    - name: lookup EC2 ID and spot_request_id
      id: get-ids
      uses: acerorg/gha-runner/ec2-lookup@MIN-340
      with:
        scope: ${{ steps.settings.outputs.scope }}
        RUNNER_NAME: ${{ inputs.name }}
        IP: ${{ steps.get-subnet-id-ip.outputs.ip_address }}

    - name: terminate EC2
      if: steps.get-ids.outputs.ec2_instance_id != ''
      uses: acerorg/gha-runner/ec2-terminate@MIN-340
      with:
        ec2_instance_id: ${{ steps.get-ids.outputs.ec2_instance_id }}
        spot_instance_request_id: ${{ steps.get-ids.outputs.spot_instance_request_id }}

    - name: Get Self-hosted Runner ID from GitHub
      id: get-runner-id
      uses: acerorg/gha-runner/get-runner-id-by-runner-name@MIN-340
      with:
        scope: ${{ steps.settings.outputs.scope }}
        token: ${{ steps.settings.outputs.token }}
        name: ${{ inputs.name }}

    - name: Remove Self-hosted Runner from GitHub
      if: steps.get-runner-id.outputs.id != ''
      shell: bash
      run: |
        if [[ "${{ steps.settings.outputs.scope }}" == "org" ]]; then
          url="${{ github.api_url }}/orgs/${{ github.repository_owner }}"
        else
          url="${{ github.api_url }}/repos/${{ github.repository }}"
        fi
        curl -X DELETE -L -o - -u "git:${{ steps.settings.outputs.token }}" -H "Accept: application/vnd.github.v3+json" \
            "${url}/actions/runners/${{ steps.get-runner-id.outputs.id }}"
