name: Update Main Version
run-name: Move ${{ inputs.main_version }} to ${{ inputs.target }}

on:
  workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true
      main_version:
        required: true
        description: The main version to update
        default: v1

jobs:
  tag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git config
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Create new tag
      run: git tag -a ${{ inputs.target }} -m 'version update'
    - name: Push new tag
      run: git push origin --tags
    - name: Tag new target
      run: git tag -f ${{ inputs.main_version }} ${{ inputs.target }}
    - name: Push new main tag
      run: git push origin ${{ inputs.main_version }} --force
